name: Update Timestamp

on:
  push:
    branches: [ main ]
    paths: 
      - 'leaderboard-data.json'  # Only trigger when JSON changes

jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update timestamp
      run: |
        # Set Morocco timezone and generate timestamp
        TZ='Africa/Casablanca' echo "$(date '+%Y/%m/%d, %H:%M')" > time.txt
        
    - name: Commit timestamp
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add time.txt
        git diff --staged --quiet || git commit -m "Auto-update timestamp"
        git push
