name: Update Timestamp

on:
  push:
    branches: [ main ]
    paths: 
      - 'leaderboard-data.json'

jobs:
  update-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update timestamp
      run: |
        # Install tzdata to ensure proper timezone handling
        sudo apt-get update && sudo apt-get install -y tzdata
        
        # Set London timezone with proper DST handling
        export TZ='Europe/London'
        echo "$(date '+%Y/%m/%d, %H:%M')" > time.txt
        
        # Debug: show what time we're using
        echo "Generated timestamp: $(cat time.txt)"
        echo "Current London time: $(date)"
        
    - name: Commit timestamp
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add time.txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update timestamp"
          git push
        fi
