name: Update Timestamp

on:
  push:
    branches: [ main ]
    paths: 
      - 'leaderboard-data.json'

jobs:
  update-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update timestamp
      run: |
        # Get Morocco time and add 1 hour manually
        morocco_plus_one=$(TZ='Africa/Casablanca' date -d '+1 hour' '+%Y/%m/%d, %H:%M')
        echo "$morocco_plus_one" > time.txt
        
    - name: Commit timestamp
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add time.txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update timestamp"
          git push
        fi
